module.exports = class NavBar{
  constructor(){
    document.querySelectorAll(".nav-toggle").forEach((el)=>{
      var nav = el.dataset.target;
      document.querySelectorAll(nav).forEach((nav_el)=>{
        el.addEventListener("click",()=>{
          nav_el.classList.add("animated")
          document.querySelectorAll(".nav-fix").forEach((e_)=>{
            e_.classList.add("animated");
          })
          if(nav_el.classList.contains("show"))
          {
            nav_el.classList.remove("show")
            nav_el.classList.add("close")
            document.querySelectorAll(".nav-fix").forEach((e_)=>{
              e_.classList.remove("fadeOut");
              e_.classList.add("fadeIn");
            })
          }
          else
          {
            nav_el.classList.add("show")
            nav_el.classList.remove("close")
            document.querySelectorAll(".nav-fix").forEach((e_)=>{
              e_.classList.remove("fadeIn");
              e_.classList.add("fadeOut");
            })
          }
        })
      })
    })
  }
}
